{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "4ee5dc5e-acdc-4071-9362-55d5f42edfad",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Medallion-Inspired Trading Signal Generator (with 3-Day High/Low)\n",
      "----------------------------------------------------------------\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter ticker (e.g. AAPL, BTC-USD, RELIANCE.NS):  v\n",
      "Benchmark (default ^GSPC, Enter to skip):  \n",
      "Years of data (default 10):  5\n",
      "Horizon days (default 3):  \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== Medallion-Inspired Analysis: V ===\n",
      "\n",
      "Feature Importance:\n",
      "bb_width        0.216605\n",
      "skew_20         0.199563\n",
      "volume_z        0.197028\n",
      "kurt_20         0.189359\n",
      "vol_ratio       0.184090\n",
      "trend_signal    0.013355\n",
      "dtype: float64\n",
      "Random Forest Test Accuracy: 47.5%\n",
      "\n",
      "Regime: neutral (prob: 97.8%)\n",
      "Final Decision: HOLD\n",
      "Position size (half-Kelly): 0.0200\n",
      "\n",
      "=== 3-DAY PRICE PROJECTION ===\n",
      "Current Price      : 318.93\n",
      "Expected Close     : 319.32  (+0.12%)\n",
      "Projected Low (5%) : 306.57      (-3.87%)\n",
      "Projected High (95%): 329.66     (+3.37%)\n",
      "\n",
      "⏸️  HOLD - Monitor the range 306.57 – 329.66\n"
     ]
    }
   ],
   "source": [
    "import yfinance as yf\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from datetime import datetime, timedelta\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.mixture import GaussianMixture\n",
    "from sklearn.model_selection import train_test_split\n",
    "from scipy.stats import skew, kurtosis\n",
    "import warnings\n",
    "\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "# =============================================================================\n",
    "# MEDALLION-INSPIRED HYBRID TRADING SYSTEM - FINAL VERSION WITH 3-DAY HIGH/LOW\n",
    "# =============================================================================\n",
    "\n",
    "def fetch_data(ticker, years=10):\n",
    "    end = datetime.today() - timedelta(days=1)\n",
    "    start = end - timedelta(days=365 * years)\n",
    "    \n",
    "    df = yf.download(ticker, start=start, end=end, auto_adjust=True, progress=False)\n",
    "    \n",
    "    if isinstance(df.columns, pd.MultiIndex):\n",
    "        df.columns = df.columns.get_level_values(0).str.lower()\n",
    "    else:\n",
    "        df.columns = df.columns.str.lower()\n",
    "    \n",
    "    expected = ['open', 'high', 'low', 'close', 'volume']\n",
    "    missing = [col for col in expected if col not in df.columns]\n",
    "    if missing:\n",
    "        raise ValueError(f\"Missing columns for {ticker}: {missing}\")\n",
    "    \n",
    "    return df[expected].dropna()\n",
    "\n",
    "\n",
    "def compute_features(df, index_df=None):\n",
    "    df = df.copy()\n",
    "    \n",
    "    df['return']     = df['close'].pct_change()\n",
    "    df['log_return'] = np.log1p(df['return'])\n",
    "    \n",
    "    df['sma_5']      = df['close'].rolling(5).mean()\n",
    "    df['sma_20']     = df['close'].rolling(20).mean()\n",
    "    df['trend_signal'] = (df['sma_5'] > df['sma_20']).astype(int)\n",
    "    \n",
    "    df['vol_10']     = df['return'].rolling(10).std()\n",
    "    df['vol_ratio']  = df['vol_10'] / df['vol_10'].rolling(60).mean()\n",
    "    \n",
    "    std20 = df['close'].rolling(20).std()\n",
    "    df['bb_mid']     = df['close'].rolling(20).mean()\n",
    "    df['bb_width']   = (2 * std20) / df['bb_mid']\n",
    "    \n",
    "    df['volume_z']   = (df['volume'] - df['volume'].rolling(50).mean()) / df['volume'].rolling(50).std()\n",
    "    \n",
    "    df['skew_20']    = df['return'].rolling(20).apply(skew, raw=True)\n",
    "    df['kurt_20']    = df['return'].rolling(20).apply(kurtosis, raw=True)\n",
    "    \n",
    "    if index_df is not None and not index_df.empty:\n",
    "        index_df = index_df.copy()\n",
    "        index_df['return'] = index_df['close'].pct_change()\n",
    "        index_df = index_df.reindex(df.index).ffill()\n",
    "        if 'return' in index_df.columns and index_df['return'].notna().any():\n",
    "            df['rel_strength'] = df['return'] - index_df['return']\n",
    "    \n",
    "    return df.dropna()\n",
    "\n",
    "\n",
    "def stationary_block_bootstrap(returns, horizon=3, sims=5000, block_size=15):\n",
    "    if len(returns) < horizon:\n",
    "        return np.ones(sims)\n",
    "    T = len(returns)\n",
    "    multipliers = np.zeros(sims)\n",
    "    \n",
    "    for i in range(sims):\n",
    "        sim_ret = []\n",
    "        while len(sim_ret) < horizon:\n",
    "            start = np.random.randint(0, T)\n",
    "            length = np.random.geometric(p=1.0 / block_size)\n",
    "            block = returns[start:start + length]\n",
    "            sim_ret.extend(block)\n",
    "        sim_ret = np.array(sim_ret[:horizon])\n",
    "        multipliers[i] = np.exp(np.sum(sim_ret))\n",
    "    \n",
    "    return multipliers\n",
    "\n",
    "\n",
    "def classify_regime(df):\n",
    "    cols = ['vol_10', 'bb_width', 'skew_20', 'kurt_20']\n",
    "    features = df[cols].dropna()\n",
    "    if len(features) < 20:\n",
    "        df['regime'] = 0\n",
    "        df['regime_prob'] = 0.50\n",
    "        return df\n",
    "    \n",
    "    gmm = GaussianMixture(n_components=3, random_state=42, covariance_type='full')\n",
    "    regimes = gmm.fit_predict(features)\n",
    "    probs = gmm.predict_proba(features)\n",
    "    \n",
    "    df = df.loc[features.index].copy()\n",
    "    df['regime'] = regimes\n",
    "    df['regime_prob'] = np.max(probs, axis=1)\n",
    "    return df\n",
    "\n",
    "\n",
    "def determine_regime(ticker, df):\n",
    "    if len(df) == 0 or 'vol_10' not in df.columns:\n",
    "        return \"neutral\"\n",
    "    vol_short = df['vol_10'].iloc[-1]\n",
    "    vol_long = df['vol_10'].rolling(60).mean().iloc[-1]\n",
    "    if pd.isna(vol_long):\n",
    "        return \"neutral\"\n",
    "    if vol_short > vol_long * 1.5:\n",
    "        return \"risk_off\"\n",
    "    elif vol_short < vol_long * 0.7:\n",
    "        return \"compression\"\n",
    "    return \"neutral\"\n",
    "\n",
    "\n",
    "def risk_metrics(multipliers, current_price):\n",
    "    rets = multipliers - 1\n",
    "    ev = rets.mean()\n",
    "    downside_prob = (rets < 0).mean()\n",
    "    tail = np.sort(rets)[:max(1, int(0.05 * len(rets)))]\n",
    "    es = tail.mean() if len(tail) > 0 else 0\n",
    "    return ev, downside_prob, es\n",
    "\n",
    "\n",
    "def expectation_agent(ev, downside_prob, es):\n",
    "    if ev > 0 and downside_prob < 0.45 and es > -0.03:\n",
    "        return \"BUY\"\n",
    "    elif ev < -0.005:\n",
    "        return \"SELL\"\n",
    "    return \"HOLD\"\n",
    "\n",
    "\n",
    "def structure_agent(df):\n",
    "    if len(df) == 0:\n",
    "        return \"BLOCK\"\n",
    "    last = df.iloc[-1]\n",
    "    if (last.get('trend_signal', 0) == 1 and \n",
    "        last.get('vol_ratio', 999) < 1.5 and \n",
    "        last.get('regime_prob', 0) > 0.6):\n",
    "        return \"ALLOW\"\n",
    "    return \"BLOCK\"\n",
    "\n",
    "\n",
    "def ml_agent(df, model):\n",
    "    if model is None:\n",
    "        return \"HOLD\"\n",
    "    features = ['trend_signal', 'vol_ratio', 'bb_width', 'volume_z', 'skew_20', 'kurt_20']\n",
    "    features = [f for f in features if f in df.columns]\n",
    "    if not features:\n",
    "        return \"HOLD\"\n",
    "    last_row = df[features].tail(1)\n",
    "    if last_row.isna().any().any():\n",
    "        return \"HOLD\"\n",
    "    prob_buy = model.predict_proba(last_row)[0, 1]\n",
    "    if prob_buy > 0.62:\n",
    "        return \"BUY\"\n",
    "    elif prob_buy < 0.38:\n",
    "        return \"SELL\"\n",
    "    return \"HOLD\"\n",
    "\n",
    "\n",
    "def final_decision(A, B, C):\n",
    "    votes = [A, B, C]\n",
    "    if \"SELL\" in votes:\n",
    "        return \"SELL\"\n",
    "    if votes.count(\"BUY\") >= 2 and B == \"ALLOW\":\n",
    "        return \"BUY\"\n",
    "    return \"HOLD\"\n",
    "\n",
    "\n",
    "def position_size(ev, vol_daily, horizon=3, max_risk=0.02):\n",
    "    if vol_daily <= 0 or ev <= 0:\n",
    "        return 0.0\n",
    "    vol_horizon = vol_daily * np.sqrt(horizon)\n",
    "    if vol_horizon == 0:\n",
    "        return 0.0\n",
    "    kelly = ev / (vol_horizon ** 2)\n",
    "    return min(max(kelly * 0.5, 0), max_risk)\n",
    "\n",
    "\n",
    "def train_model_with_importance(df):\n",
    "    if len(df) < 100:\n",
    "        return None, None, 0.0\n",
    "    \n",
    "    df = df.copy()\n",
    "    df['target'] = (df['close'].shift(-1) > df['close']).astype(int)\n",
    "    df = df.dropna()\n",
    "    \n",
    "    if len(df) < 50:\n",
    "        return None, None, 0.0\n",
    "    \n",
    "    features = ['trend_signal', 'vol_ratio', 'bb_width', 'volume_z', 'skew_20', 'kurt_20']\n",
    "    features = [f for f in features if f in df.columns]\n",
    "    \n",
    "    if not features:\n",
    "        return None, None, 0.0\n",
    "    \n",
    "    X, y = df[features], df['target']\n",
    "    Xtr, Xte, ytr, yte = train_test_split(X, y, shuffle=False, test_size=0.2, random_state=42)\n",
    "    \n",
    "    model = RandomForestClassifier(n_estimators=400, max_depth=7, random_state=42, n_jobs=-1)\n",
    "    model.fit(Xtr, ytr)\n",
    "    \n",
    "    importance = pd.Series(model.feature_importances_, index=features).sort_values(ascending=False)\n",
    "    accuracy = model.score(Xte, yte)\n",
    "    \n",
    "    return model, importance, accuracy\n",
    "\n",
    "\n",
    "def run_system(ticker, benchmark=\"^GSPC\", years=10, horizon=3, sims=5000):\n",
    "    print(f\"\\n=== Medallion-Inspired Analysis: {ticker} ===\")\n",
    "    try:\n",
    "        df = fetch_data(ticker, years=years)\n",
    "        index_df = fetch_data(benchmark, years=years) if benchmark else None\n",
    "    except Exception as e:\n",
    "        print(f\"Download error: {e}\")\n",
    "        return\n",
    "    \n",
    "    df = compute_features(df, index_df)\n",
    "    df = classify_regime(df)\n",
    "    \n",
    "    if len(df) < 60:\n",
    "        print(\"Not enough clean data after feature engineering.\")\n",
    "        return\n",
    "    \n",
    "    model, importance, accuracy = train_model_with_importance(df)\n",
    "    if model is not None:\n",
    "        print(\"\\nFeature Importance:\")\n",
    "        print(importance.head(8))\n",
    "        print(f\"Random Forest Test Accuracy: {accuracy*100:.1f}%\")\n",
    "    \n",
    "    # Bootstrap simulation\n",
    "    recent_returns = df['log_return'].tail(400).values\n",
    "    multipliers = stationary_block_bootstrap(recent_returns, horizon=horizon, sims=sims)\n",
    "    current_price = df['close'].iloc[-1]\n",
    "    sim_prices = current_price * multipliers\n",
    "    \n",
    "    ev, downside_prob, es = risk_metrics(multipliers, current_price)\n",
    "    \n",
    "    A = expectation_agent(ev, downside_prob, es)\n",
    "    B = structure_agent(df)\n",
    "    C = ml_agent(df, model)\n",
    "    decision = final_decision(A, B, C)\n",
    "    \n",
    "    vol = df['vol_10'].iloc[-1] if 'vol_10' in df.columns else 0\n",
    "    size = position_size(ev, vol, horizon=horizon)\n",
    "    regime = determine_regime(ticker, df)\n",
    "    \n",
    "    # 3-DAY HIGH / LOW / BUY / SELL SUGGESTIONS\n",
    "    proj_low       = np.percentile(sim_prices, 5)\n",
    "    proj_high      = np.percentile(sim_prices, 95)\n",
    "    proj_expected  = sim_prices.mean()\n",
    "    \n",
    "    print(f\"\\nRegime: {regime} (prob: {df['regime_prob'].iloc[-1]:.1%})\")\n",
    "    print(f\"Final Decision: {decision}\")\n",
    "    print(f\"Position size (half-Kelly): {size:.4f}\")\n",
    "    \n",
    "    print(f\"\\n=== 3-DAY PRICE PROJECTION ===\")\n",
    "    print(f\"Current Price      : {current_price:.2f}\")\n",
    "    print(f\"Expected Close     : {proj_expected:.2f}  ({(proj_expected/current_price-1)*100:+.2f}%)\")\n",
    "    print(f\"Projected Low (5%) : {proj_low:.2f}      ({(proj_low/current_price-1)*100:+.2f}%)\")\n",
    "    print(f\"Projected High (95%): {proj_high:.2f}     ({(proj_high/current_price-1)*100:+.2f}%)\")\n",
    "    \n",
    "    if decision == \"BUY\":\n",
    "        print(f\"\\n✅ BUY Suggestion:\")\n",
    "        print(f\"   • Enter near or below : {proj_low:.2f} (3-day low estimate)\")\n",
    "        print(f\"   • Stop-loss below     : {proj_low * 0.985:.2f}\")\n",
    "    elif decision == \"SELL\":\n",
    "        print(f\"\\n❌ SELL Suggestion:\")\n",
    "        print(f\"   • Target near or above: {proj_high:.2f} (3-day high estimate)\")\n",
    "        print(f\"   • Stop-loss above     : {proj_high * 1.015:.2f}\")\n",
    "    else:\n",
    "        print(f\"\\n⏸️  HOLD - Monitor the range {proj_low:.2f} – {proj_high:.2f}\")\n",
    "    \n",
    "    if model is not None:\n",
    "        try:\n",
    "            prob_buy = model.predict_proba(df[importance.index].tail(1))[0,1]\n",
    "            print(f\"\\nML Buy Probability: {prob_buy:.1%}\")\n",
    "        except:\n",
    "            pass\n",
    "\n",
    "\n",
    "# ─── INTERACTIVE MODE ────────────────────────────────────────────────────────\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"Medallion-Inspired Trading Signal Generator (with 3-Day High/Low)\")\n",
    "    print(\"----------------------------------------------------------------\")\n",
    "    \n",
    "    ticker = input(\"Enter ticker (e.g. AAPL, BTC-USD, RELIANCE.NS): \").strip().upper()\n",
    "    if not ticker:\n",
    "        ticker = \"AAPL\"\n",
    "        print(\"Default: AAPL\")\n",
    "    \n",
    "    benchmark_input = input(\"Benchmark (default ^GSPC, Enter to skip): \").strip()\n",
    "    benchmark = benchmark_input if benchmark_input else \"^GSPC\"\n",
    "    \n",
    "    try:\n",
    "        years = int(input(\"Years of data (default 10): \") or 10)\n",
    "    except:\n",
    "        years = 10\n",
    "    \n",
    "    try:\n",
    "        horizon = int(input(\"Horizon days (default 3): \") or 3)\n",
    "    except:\n",
    "        horizon = 3\n",
    "    \n",
    "    run_system(ticker, benchmark=benchmark, years=years, horizon=horizon, sims=5000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "29f28e2b-dfef-4aa0-9c94-2636da943939",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
